### ISSUE TITLE
Feature Request: Upgrade to ESLint 9

### ISSUE THREAD

**Issue by joncursi** [nrccua/eslint-config#42]
Blockers:

- [ ] `eslint-config-airbnb` -- waiting on https://github.com/airbnb/javascript/issues/2961
- [ ] `eslint-plugin-import` -- waiting on https://github.com/import-js/eslint-plugin-import/issues/2948
- [ ] `eslint-plugin-filenames` -- waiting on https://github.com/selaux/eslint-plugin-filenames/issues/54
  * Possible alternative: `eslint-plugin-filenames-simple` -- waiting on https://github.com/epaew/eslint-plugin-filenames-simple/issues/705

Non-blocking, but only implementable through [compatibility utilities](https://eslint.org/blog/2024/05/eslint-compatibility-utilities/):

- [x] `eslint-plugin-disable` -- https://github.com/mradionov/eslint-plugin-disable
- [x] `eslint-plugin-lodash` -- https://www.npmjs.com/package/eslint-plugin-lodash
- [x] `eslint-plugin-new-with-error` -- https://www.npmjs.com/package/eslint-plugin-new-with-error
- [x] `eslint-plugin-no-loops` -- https://www.npmjs.com/package/eslint-plugin-no-loops
- [x] `eslint-plugin-react-hooks`: available in canary, but not formally released yet

**Comment by joncursi** [comment]
See https://github.com/act-org/eslint-config/pull/20 for reference
